match('aubrey') { set place: 'aubrey' }
match('brickeys') { set place: 'brickeys' }
match('haynes') { set place: 'haynes' }
match('lagrange') { set place: 'lagrange' }
match('marianna') { set place: 'marianna' }
match('midway') { set place: 'midway' }
match('monroe') { set place: 'monroe' }
match('moro') { set place: 'moro' }
match('rondo') { set place: 'rondo' }
