match('agenda') { set place: 'agenda' }
match('belleville') { set place: 'belleville' }
match('courtland') { set place: 'courtland' }
match('cuba') { set place: 'cuba' }
match('kackley') { set place: 'kackley' }
match('munden') { set place: 'munden' }
match('narka') { set place: 'narka' }
match('norway') { set place: 'norway' }
match('republic') { set place: 'republic' }
match('scandia') { set place: 'scandia' }
match('wayne') { set place: 'wayne' }
